### ISSUE TITLE
Lintly GitHub Actions has stopped working in the last few days

### ISSUE THREAD

**Issue by JMMarchant** [grantmcconnaughey/Lintly#41]
We've been using Lintly and flake8 on our GitHub Actions but over the last few days it seems to have stopped working (no longer posts PR approvals or reviews). Was just wondering if there had been any changes that might explain it; the job is running and finished, it just doesn't post the review/approval.

Here's out GitHub Actions config:
```
name: Lint

on: [pull_request]

jobs:
  # Black formatting check
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Run Black code formatter
        uses: psf/black@stable

  # flake8 check
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install flake8 and plugins
        run: pip install \
                flake8 \
                flake8-bugbear \
                lintly
      - name: Run flake8 linter
        run: flake8 | lintly
        env:
          LINTLY_API_KEY: ${{ secrets.GITHUB_TOKEN }}
```
